const API="https://api.github.com";let token="",repo="",sha="",products=[];const $=id=>document.getElementById(id);
function msg(t,ok=true){$("status").innerHTML='<div class="'+(ok?"ok":"err")+'">'+t+"</div>";}
function loginMsg(t,ok=true){$("login-status").innerHTML='<div class="'+(ok?"ok":"err")+'">'+t+"</div>";}
async function gh(path,opts={}){const r=await fetch(API+path,{...opts,headers:{Accept:"application/vnd.github+json","Authorization":"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json",...(opts.headers||{})}});if(!r.ok)throw new Error((await r.text()).slice(0,500));return r.json();}
function parseProducts(src){const m=src.match(/const PRODUCTS\s*=\s*(\[[\s\S]*?\]);/);if(!m)throw new Error("Could not read products.js");return Function("return "+m[1])();}
function source(){return "/* FARMTEK09 CENTRE — shared GitHub catalogue. */\\nconst PRODUCTS = "+JSON.stringify(products,null,2)+";\\n\\nif (typeof module !== \"undefined\") module.exports = PRODUCTS;\\n";}
async function load(){const d=await gh("/repos/"+repo+"/contents/products.js?ref=main");sha=d.sha;const src=decodeURIComponent(escape(atob(d.content.replace(/\n/g,""))));products=parseProducts(src);render();$("login").hidden=true;$("dashboard").hidden=false;}
function render(){const rows=$("rows");rows.innerHTML=products.map((p,i)=>'<tr><td><img class="thumb" src="'+esc(p.image)+'"></td><td><b>'+esc(p.name)+'</b><br><small>'+esc(p.id)+'</small></td><td>KES '+Number(p.price).toLocaleString("en-KE")+'</td><td class="'+(p.stock>0?"in":"sold")+'">'+p.stock+'</td><td>'+esc(p.unit)+'</td><td class="actions"><button onclick="edit('+i+')">Edit</button><button class="danger" onclick="del('+i+')">Delete</button></td></tr>').join("");$("stats").innerHTML='<div class="stats"><div class="stat"><b>'+products.length+'</b><br>Products</div><div class="stat"><b>'+products.reduce((s,p)=>s+Number(p.stock||0),0)+'</b><br>Total Stock</div><div class="stat"><b>KES '+Math.min(...products.map(p=>p.price)).toLocaleString("en-KE")+'</b><br>Lowest Price</div></div>';}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function edit(i){const p=products[i];$("modal-title").textContent="Edit Product";$("old-id").value=p.id;$("pid").value=p.id;$("pid").disabled=true;$("pname").value=p.name;$("price").value=p.price;$("stock").value=p.stock??0;$("unit").value=p.unit||"seedling";$("image").value=p.image||"";$("description").value=p.description||"";$("modal").hidden=false;}
function add(){ $("modal-title").textContent="Add Product";$("old-id").value="";$("pid").disabled=false;["pid","pname","image","description"].forEach(id=>$(id).value="");$("price").value=0;$("stock").value=0;$("unit").value="seedling";$("modal").hidden=false;}
function del(i){if(confirm("Delete "+products[i].name+" from the live GitHub catalogue?")){products.splice(i,1);commit("Delete product");}}
async function commit(message){try{msg("Committing changes to GitHub…");const body=btoa(unescape(encodeURIComponent(source())));const d=await gh("/repos/"+repo+"/contents/products.js",{method:"PUT",body:JSON.stringify({message,content:body,sha,branch:"main"})});sha=d.content.sha;render();msg("Saved. GitHub Pages will publish the customer catalogue from the updated products.js.");}catch(e){msg("GitHub save failed: "+e.message,false);}}
$("connect").onclick=async()=>{token=$("token").value.trim();repo=$("repo").value.trim();if(!token||!repo)return loginMsg("Enter your GitHub token and repository.",false);try{await load();loginMsg("Connected.");}catch(e){loginMsg("Connection failed: "+e.message,false);}};
$("new").onclick=add;$("close").onclick=$("cancel").onclick=()=>{$("modal").hidden=true};
$("product-form").onsubmit=async e=>{e.preventDefault();const p={id:$("pid").value.trim(),name:$("pname").value.trim(),price:Number($("price").value),stock:Number($("stock").value),unit:$("unit").value.trim(),image:$("image").value.trim(),description:$("description").value.trim()};const old=$("old-id").value;if(old){const i=products.findIndex(x=>x.id===old);products[i]=p;}else{if(products.some(x=>x.id===p.id))return alert("Product ID already exists.");products.push(p);} $("modal").hidden=true;await commit(old?"Update product "+p.id:"Add product "+p.id);};
window.edit=edit;window.del=del;